project:
  type: website
  resources:
    - cv.pdf
    
website:
  title: "Aly Tan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching
      - href: courses.qmd
        text: Courses
      - href: projects.qmd
        text: Projects
        
  page-footer: 
    right: "&copy; 2025, Aly Tan"
        
format:
  html:
    theme:
      light: [cosmo]
      dark: [cosmo]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true



execute: 
  freeze: auto