project:
  type: website

website:
  title: "Aly Tan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
        
  page-footer: 
    right: "&copy; 2025, Aly Tan"
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    published-title: "last updated"
    reference-location: document
    code-fold: false
    code-summary: ""
    fontsize: 1.3em



execute: 
  freeze: auto